apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: asdasdasd
  description: asdasdasdasd
  annotations: 
    github.com/project-slug: blamdemo/asdaionegb
    backstage.io/github-actions-id: blamdemo/asdaionegb
spec:
  type: service
  lifecycle: experimental
  owner: guest
